### ISSUE TITLE
"Modernize" RLP.sol - Remove Linter Errors Etc

### ISSUE THREAD

**Issue by relyt29** [lorenzb/proveth#20]
RLP.sol has a bunch of linter warnings with modern solidity compilers. We should eventually get around to updating the version of solidity expected by RLP.sol and make as many of the linter warnings go away as possible

**Comment by lorenzb** [comment]
Switched to https://github.com/hamdiallam/Solidity-RLP in commit 41b45f2 per @izqui's suggestion
